spring:
  config:
    import: classpath:config.yml

  profiles:
    active: local

  application:
    name: common

  datasource:
    username: com_dev
    password: qwer1234!
  hikari:
    connection-timeout: 30000
    maximum-pool-size: 10

springdoc:
  api-docs:
    path: "/com/common/docs" # 접속 path 설정
    #enabled: false
  swagger-ui:
    path: "/com/common/swagger-ui" # 접속 path 설정
    display-request-duration: true  # try it out 을 했을 때 request duration 을 추가로 찍어줌
    #enabled: false
  cache:
    disabled: true # swagger cache 설정

app:
  secret-key: 6fl4oppus58ggi3uxnckbw1s13048caf
---

spring:
  config:
    activate:
      on-profile: local-env

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: "changeme"
      timeout: 30000
      lettuce:
        pool:
          maxTotal: 8
          maxWaitMillis: 10000
          maxIdle: 8
          minIdle: 0

feign:
  account-service.url: http://localhost:9101
  authorization-service.url: http://localhost:9101

server:
  port: 9100

#logging:
#  level:
#    kr.co.skcc.base: DEBUG
#    org.hibernate.SQL: DEBUG
---

spring:
  config:
    activate:
      on-profile: dev-env

  data:
    redis:
      database: 0
      host: redis.temp-infra.svc.cluster.local
      port: 6379
      password: "changeme"
      timeout: 30000
      lettuce:
        pool:
          maxTotal: 8
          maxWaitMillis: 10000
          maxIdle: 8
          minIdle: 0

feign:
  account-service.url: http://account:8080
  authorization-service.url: http://account:8080

---

spring:
  config:
    activate:
      on-profile: stg-env
---

spring:
  config:
    activate:
      on-profile: prd-env