version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: keycloak-common
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"
