apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kafka
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-kafka
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kafka
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9092
              name: kafka
          env:
            - name: KAFKA_BROKER_ID
              value: {{ .Values.env.KAFKA_BROKER_ID | quote }}
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ .Values.env.KAFKA_ZOOKEEPER_CONNECT | quote }}
            - name: KAFKA_LISTENERS
              value: {{ .Values.env.KAFKA_LISTENERS | quote }}
            - name: KAFKA_ADVERTISED_LISTENERS
              value: {{ .Values.env.KAFKA_ADVERTISED_LISTENERS | quote }}
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: {{ .Values.env.KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR | quote }}
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: {{ .Values.env.KAFKA_AUTO_CREATE_TOPICS_ENABLE | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }} 