replicaCount: 1

namespace: temp-infra

image:
  repository: wurstmeister/kafka
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

env:
  KAFKA_BROKER_ID: -1
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_LISTENERS: PLAINTEXT://:9092
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-kafka.temp-infra.svc.cluster.local:9092
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" 