apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          command: ["redis-server"]
          args: ["--requirepass", "{{ .Values.redisPassword }}", "--port", "{{ .Values.service.targetPort }}"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        agentpool: agent2 