replicaCount: 1

image:
  repository: agsats.azurecr.io/account-service
  pullPolicy: Always
  tag: "0.1.0"

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: TZ
    value: "Asia/Seoul" 