replicaCount: 1

image:
  repository: redis
  tag: 6.2.6
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379
  targetPort: 6379

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

redisPassword: "changeme" 